Cadeteria/Models/Cadete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadeteriaMVC.Models
{
    public class Cadete : Entity
    {
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Cadeteria Cadeteria { get; set; }

        public Cadete()
        {

        }

    }
}

Cadeteria/Models/Cadeteria.cs
using CadeteriaMVC.Models;
using System;
using System.Collections.Generic;

namespace CadeteriaMVC.Models
{
    public class Cadeteria : Entity
    {
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public List<Cadeteria> ListadoCadetes { get; set; }

        public Cadeteria()
        {

        }
        public Cadeteria(string nombre, string direccion)
        {
            Nombre = nombre;
            Direccion = direccion;
        }




    }
}

Cadeteria/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadeteriaMVC.Models
{
    public class Cliente : Entity
    {
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }

    }
}

Cadeteria/Models/ErrorViewModel.cs
using System;

namespace Cadetes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cadeteria/Models/Pedido.cs
using CadeteriaMVC.Models;

public enum Estado
{
    EnCamino,
    Entregado,
    Cancelado
}
public class Pedido : Entity
{
    public string Observacion { get; set; }
    public Cliente Cliente { get; set; }
    public Estado Estado { get; set; }
    
    public Pedido(int id, string observacion, Cliente cliente)
    {
        this.Id = id;
        this.Estado = 0;
        this.Observacion = observacion;
        this.Cliente = cliente;
    }

    public Pedido()
    {

    }

  
}

Cadeteria/Models/Usuario.cs
using CadeteriaMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cadeteria.Models
{
    public class Usuario : Entity
    {
        public string Nombre { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}

Cadeteria/Models/ViewModels/PedidoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CadeteriaMVC.Models.ViewModels
{
    public class PedidoViewModel
    {
        [Required(ErrorMessage ="Este campo es requerido")]
        public int Nro { get; set; }
        [Required]
        public string Observacion { get; set; }
        [Required]
        public string Nombre_Cliente { get; set; }
        [Required]
        public Estado Estado { get; set; }

        [Required]
        public string Telefono { get; set; }

        [Required]
        public string Direccion { get; set; }

    }
}

Cadeteria/Controllers/CadetesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cadetes.Models;
using CadeteriaMVC.Interfaces;
using CadeteriaMVC.Models;

namespace Cadetes.Controllers
{
    public class CadetesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICadeteRepository _repo;

        public CadetesController(ILogger<HomeController> logger, ICadeteRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index()
        {
            List<Cadete> cadetes = _repo.GetAll();
            return View(cadetes);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadeteria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cadetes.Models;

namespace Cadetes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("sesion", "probando");
            return View();
        }

        public IActionResult Privacy()
        {

                string prueba = HttpContext.Session.GetString("sesion");
            ViewData["prueba"] = prueba;
            

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadeteria/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cadetes.Models;
using CadeteriaMVC.Models.ViewModels;
using CadeteriaMVC.Helpers;
using CadeteriaMVC.Interfaces;
using CadeteriaMVC.Models;

namespace Cadetes.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPedidosRepository _repo;
        public PedidoController(ILogger<HomeController> logger, IPedidosRepository repo)
        {
            _logger = logger;
            _repo = repo;

        }

        public IActionResult Index()
        {
            List<Pedido> pedidos = _repo.GetAll();
            List<PedidoViewModel> pedidosViewModel = Mapper.PedidosToPedidosVM(pedidos);
            return View(pedidosViewModel);
        }
        [HttpGet]
        public IActionResult AddPedido()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddPedido(string nombre, string direccion, string obs, string telefono)
        {
            //Cliente cliente = new Cliente(nombre, direccion, telefono, direccion, null);
            //Pedido pedido = new Pedido(obs, cliente);
            //HelperArchivos.InsertCliente(cliente);
            //HelperArchivos.InsertPedido(pedido);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Pedido nPedido = _repo.GetById(id);
            PedidoViewModel pedidoVM = Mapper.PedidoToPedidoVM(nPedido);

            return View(pedidoVM);
        }

        
        public IActionResult Delete(int id)
        {
            Pedido nPedido = _repo.GetById(id);
            PedidoViewModel pedidoVM = Mapper.PedidoToPedidoVM(nPedido);

            return View(pedidoVM);
        
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            _repo.DeletePedido(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public IActionResult Create(PedidoViewModel pedido)
        {
            Cliente cliente = new Cliente()
            {
                Id = _repo.GetLastIdCliente(),
                Telefono = pedido.Telefono,
                Nombre = pedido.Nombre_Cliente,
                Direccion = pedido.Direccion
            };

        
            return RedirectToAction("Index");

            
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadeteria/Views/Cadetes/Index.cshtml
@model IEnumerable<CadeteriaMVC.Models.Cadete>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Cadeteria/Views/Pedido/Create.cshtml
@model CadeteriaMVC.Models.ViewModels.PedidoViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PedidoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

             <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observacion" class="control-label"></label>
                <input asp-for="Observacion" class="form-control" />
                <span asp-validation-for="Observacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Cliente" class="control-label"></label>
                <input asp-for="Nombre_Cliente" class="form-control" />
                <span asp-validation-for="Nombre_Cliente" class="text-danger"></span>
            </div>
                <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">

              <select asp-for="Estado" asp-items="Html.GetEnumSelectList<Estado>()">
            <option value="">Estado del Pedido</option>
            </select>
               
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Cadeteria/Views/Pedido/Delete.cshtml
@model CadeteriaMVC.Models.ViewModels.PedidoViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PedidoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Cliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cadeteria/Views/Pedido/Details.cshtml
@model CadeteriaMVC.Models.ViewModels.PedidoViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PedidoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Cliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Cadeteria/Views/Pedido/Index.cshtml
@model IEnumerable<CadeteriaMVC.Models.ViewModels.PedidoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Observacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_Cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Nro  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Nro  })
            </td>
        </tr>
}
    </tbody>
</table>

Cadeteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadeteriaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadeteriaMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadeteriaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadetes" asp-action="Index">Cadetes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CadeteriaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>